[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  base = "."

[build.environment]
  REACT_APP_API_URL = "https://tastetrail-f3gc.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
